lst=["apple","45","245.5","kiwi","1"]
lst.append("grapes")
print(lst)
lst.sort()
print(lst)
lst.extend(["orange", "banana"])
print(lst)
lst.reverse()
print(lst)
lst.insert(0,"mango")
print(lst)
lst.pop(2)
print(lst)
lst.remove("kiwi")
print(lst)